### ISSUE TITLE
🪲[BUG] error

### ISSUE THREAD

**Issue by AllLuckly** [feduke-nukem/flutter_easy_dialogs#18]
my class is  StatefulWidget
···
  static EasyDialogsController get controller => _key.currentState!.controller;
···

···
======== Exception caught by gesture ===============================================================
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      FlutterEasyDialogs.controller (package:flutter_easy_dialogs/src/flutter_easy_dialogs.dart:22:67)
#1      FlutterEasyDialogs.show (package:flutter_easy_dialogs/src/flutter_easy_dialogs.dart:26:7)
#2      EasyDialogsX.show (package:flutter_easy_dialogs/src/core/easy_dialogs_controller.dart:548:62)
···

**Comment by feduke-nukem** [comment]
> my class is StatefulWidget ··· static EasyDialogsController get controller => _key.currentState!.controller; ···
> 
> ··· ======== Exception caught by gesture =============================================================== The following _TypeError was thrown while handling a gesture: Null check operator used on a null value
> 
> When the exception was thrown, this was the stack: #0 FlutterEasyDialogs.controller (package:flutter_easy_dialogs/src/flutter_easy_dialogs.dart:22:67) #1 FlutterEasyDialogs.show (package:flutter_easy_dialogs/src/flutter_easy_dialogs.dart:26:7) #2 EasyDialogsX.show (package:flutter_easy_dialogs/src/core/easy_dialogs_controller.dart:548:62) ···

Hello,

Did you wrap your material application with ```FlutterEasyDialogs.builder()```? 
Like so:

```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: FlutterEasyDialogs.builder(),
    );
  }
}
```

**Comment by feduke-nukem** [comment]
@AllLuckly Does the problem persist? I will close the issue otherwise

**Comment by feduke-nukem** [comment]
@AllLuckly, I am closing this issue for now as there has been no activity. Feel free to reopen the issue if the problem arises again.
